export const data = JSON.parse("{\"key\":\"v-8daa1a0e\",\"path\":\"/\",\"title\":\"主页\",\"lang\":\"zh-CN\",\"frontmatter\":{\"home\":true,\"icon\":\"home\",\"title\":\"主页\",\"bgImage\":\"https://theme-hope-assets.vuejs.press/bg/6-light.svg\",\"bgImageDark\":\"https://theme-hope-assets.vuejs.press/bg/6-dark.svg\",\"bgImageStyle\":{\"background-attachment\":\"fixed\"},\"heroText\":\"科哒的星空世界技术之路\",\"tagline\":\"技术的星空之下，步步探索，留下足迹，分享和记录技术成长之路\",\"actions\":[{\"text\":\"开始阅读 👣\",\"link\":\"./md/\",\"type\":\"primary\"}],\"highlights\":[{\"header\":null,\"bgImage\":\"/assets/bg/6-light.svg\",\"bgImageDark\":\"/assets/bg/6-dark.svg\",\"features\":[{\"title\":\"公众号 - 抽奖系统\",\"icon\":\"comment-dots\",\"details\":\"23年1月，以DDD领域驱动设计架构，开发完成分布式抽奖系统。运用了全面的分布式技术栈。\",\"link\":\"https://theme-hope.vuejs.press/zh/guide/markdown/others.html#link-check\"},{\"title\":\"手写 MyBatis\",\"icon\":\"box-archive\",\"details\":\"23年4月，深度学习《手写MyBatis：渐进式源码实践》一书，完整实现了一个 MyBatis ORM 框架。\",\"link\":\"https://theme-hope.vuejs.press/zh/guide/markdown/container.html\"},{\"title\":\"OpenAI 应用服务\",\"icon\":\"table-columns\",\"details\":\"23年8月，学习 OpenAi 技术，学习 OpenAi SDK 开发，完成应用场景的对接使用「涵盖支付对接」。\",\"link\":\"https://theme-hope.vuejs.press/zh/guide/markdown/tabs.html\"}]}],\"copyright\":false,\"footer\":\"<div class=\\\"content\\\"><a href=\\\"http://beian.miit.gov.cn\\\" target=\\\"_blank\\\">京ICP备1903****号</a> | MIT 协议, 版权所有 © 2023 你的名字，All rights reserved.</div>\",\"description\":\"::: tip 个人在大学/实习期间，参与过多次的技术类赛事项目，熟练使用各类技术框架，积累了丰富的开发经验。同时兼具着对技术的喜爱，长期对技术源码进行钻研学习吸收其中的设计精髓。尤其对 MyBatis 源码学习后，开发了一款监控 SQL 慢查询以及优化建议插件。并将此插件发布到了 IDEA Plugin 插件市场，半年获得了3000次下载量，获得了非...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"科哒的技术博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"主页\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"::: tip 个人在大学/实习期间，参与过多次的技术类赛事项目，熟练使用各类技术框架，积累了丰富的开发经验。同时兼具着对技术的喜爱，长期对技术源码进行钻研学习吸收其中的设计精髓。尤其对 MyBatis 源码学习后，开发了一款监控 SQL 慢查询以及优化建议插件。并将此插件发布到了 IDEA Plugin 插件市场，半年获得了3000次下载量，获得了非...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"科哒\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"WebPage\\\",\\\"name\\\":\\\"主页\\\",\\\"description\\\":\\\"::: tip 个人在大学/实习期间，参与过多次的技术类赛事项目，熟练使用各类技术框架，积累了丰富的开发经验。同时兼具着对技术的喜爱，长期对技术源码进行钻研学习吸收其中的设计精髓。尤其对 MyBatis 源码学习后，开发了一款监控 SQL 慢查询以及优化建议插件。并将此插件发布到了 IDEA Plugin 插件市场，半年获得了3000次下载量，获得了非...\\\"}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":2.07,\"words\":621},\"filePathRelative\":\"README.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
